//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORIA> CATEGORIA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual int SP_CREATE_CATEGORIA(string v_NOMBRE)
        {
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CATEGORIA", v_NOMBREParameter);
        }
    
        public virtual int SP_CREATE_PRODUCTO(string v_NOMBRE, string v_PRECIO, Nullable<decimal> v_STOCK, string v_IMAGEN, Nullable<decimal> v_CATEGORIA_ID)
        {
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_PRECIOParameter = v_PRECIO != null ?
                new ObjectParameter("V_PRECIO", v_PRECIO) :
                new ObjectParameter("V_PRECIO", typeof(string));
    
            var v_STOCKParameter = v_STOCK.HasValue ?
                new ObjectParameter("V_STOCK", v_STOCK) :
                new ObjectParameter("V_STOCK", typeof(decimal));
    
            var v_IMAGENParameter = v_IMAGEN != null ?
                new ObjectParameter("V_IMAGEN", v_IMAGEN) :
                new ObjectParameter("V_IMAGEN", typeof(string));
    
            var v_CATEGORIA_IDParameter = v_CATEGORIA_ID.HasValue ?
                new ObjectParameter("V_CATEGORIA_ID", v_CATEGORIA_ID) :
                new ObjectParameter("V_CATEGORIA_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_PRODUCTO", v_NOMBREParameter, v_PRECIOParameter, v_STOCKParameter, v_IMAGENParameter, v_CATEGORIA_IDParameter);
        }
    
        public virtual int SP_DELETE_CATEGORIA(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_CATEGORIA", v_IDParameter);
        }
    
        public virtual int SP_DELETE_PRODUCTO(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_PRODUCTO", v_IDParameter);
        }
    
        public virtual int SP_UPDATE_CATEGORIA(Nullable<decimal> v_ID, string v_NOMBRE)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CATEGORIA", v_IDParameter, v_NOMBREParameter);
        }
    
        public virtual int SP_UPDATE_PRODUCTO(Nullable<decimal> v_ID, string v_NOMBRE, string v_PRECIO, Nullable<decimal> v_STOCK, string v_IMAGEN, Nullable<decimal> v_CATEGORIA_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_PRECIOParameter = v_PRECIO != null ?
                new ObjectParameter("V_PRECIO", v_PRECIO) :
                new ObjectParameter("V_PRECIO", typeof(string));
    
            var v_STOCKParameter = v_STOCK.HasValue ?
                new ObjectParameter("V_STOCK", v_STOCK) :
                new ObjectParameter("V_STOCK", typeof(decimal));
    
            var v_IMAGENParameter = v_IMAGEN != null ?
                new ObjectParameter("V_IMAGEN", v_IMAGEN) :
                new ObjectParameter("V_IMAGEN", typeof(string));
    
            var v_CATEGORIA_IDParameter = v_CATEGORIA_ID.HasValue ?
                new ObjectParameter("V_CATEGORIA_ID", v_CATEGORIA_ID) :
                new ObjectParameter("V_CATEGORIA_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_PRODUCTO", v_IDParameter, v_NOMBREParameter, v_PRECIOParameter, v_STOCKParameter, v_IMAGENParameter, v_CATEGORIA_IDParameter);
        }
    
        public virtual int PRODUCTO_INSERTAR(string v_NOMBRE, string v_PRECIO, Nullable<decimal> v_STOCK, string v_IMAGEN, Nullable<decimal> v_CATEGORIA_ID, ObjectParameter iD_GENERADO)
        {
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_PRECIOParameter = v_PRECIO != null ?
                new ObjectParameter("V_PRECIO", v_PRECIO) :
                new ObjectParameter("V_PRECIO", typeof(string));
    
            var v_STOCKParameter = v_STOCK.HasValue ?
                new ObjectParameter("V_STOCK", v_STOCK) :
                new ObjectParameter("V_STOCK", typeof(decimal));
    
            var v_IMAGENParameter = v_IMAGEN != null ?
                new ObjectParameter("V_IMAGEN", v_IMAGEN) :
                new ObjectParameter("V_IMAGEN", typeof(string));
    
            var v_CATEGORIA_IDParameter = v_CATEGORIA_ID.HasValue ?
                new ObjectParameter("V_CATEGORIA_ID", v_CATEGORIA_ID) :
                new ObjectParameter("V_CATEGORIA_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRODUCTO_INSERTAR", v_NOMBREParameter, v_PRECIOParameter, v_STOCKParameter, v_IMAGENParameter, v_CATEGORIA_IDParameter, iD_GENERADO);
        }
    
        public virtual int PRODUCTO_ACTUALIZAR(Nullable<decimal> v_ID, string v_NOMBRE, string v_PRECIO, Nullable<decimal> v_STOCK, string v_IMAGEN, Nullable<decimal> v_CATEGORIA_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            var v_NOMBREParameter = v_NOMBRE != null ?
                new ObjectParameter("V_NOMBRE", v_NOMBRE) :
                new ObjectParameter("V_NOMBRE", typeof(string));
    
            var v_PRECIOParameter = v_PRECIO != null ?
                new ObjectParameter("V_PRECIO", v_PRECIO) :
                new ObjectParameter("V_PRECIO", typeof(string));
    
            var v_STOCKParameter = v_STOCK.HasValue ?
                new ObjectParameter("V_STOCK", v_STOCK) :
                new ObjectParameter("V_STOCK", typeof(decimal));
    
            var v_IMAGENParameter = v_IMAGEN != null ?
                new ObjectParameter("V_IMAGEN", v_IMAGEN) :
                new ObjectParameter("V_IMAGEN", typeof(string));
    
            var v_CATEGORIA_IDParameter = v_CATEGORIA_ID.HasValue ?
                new ObjectParameter("V_CATEGORIA_ID", v_CATEGORIA_ID) :
                new ObjectParameter("V_CATEGORIA_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRODUCTO_ACTUALIZAR", v_IDParameter, v_NOMBREParameter, v_PRECIOParameter, v_STOCKParameter, v_IMAGENParameter, v_CATEGORIA_IDParameter);
        }
    
        public virtual int PRODUCTO_ELIMINAR(Nullable<decimal> v_ID)
        {
            var v_IDParameter = v_ID.HasValue ?
                new ObjectParameter("V_ID", v_ID) :
                new ObjectParameter("V_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRODUCTO_ELIMINAR", v_IDParameter);
        }
    }
}
